
// next
import Head from 'next/head';
import { useRouter } from 'next/router';

// components
import Navbar from '../client_modules/components/Navbar/Navbar';
import NavDropDown from '../client_modules/components/DropDowns/NavDropDown/NavDropDown';
import { AppLayout, AppLayOutItems } from '../client_modules/styled_components/aligment';
import Settings from '../client_modules/components/Settings/Settings';
import ActionButton from '../client_modules/components/ActionButton/ActionButton';
import TodoDropDown from '../client_modules/components/DropDowns/TodoDropDown/TodoDropDown';
import Todos from '../client_modules/components/Todo/Todo';

// react
import React, { useEffect, useRef, useState } from 'react';
import { useGlobalState } from '../client_modules/hooks/useGlobalStateHook';
import { dispatchUserState } from '../client_modules/hooks/useDispatchUserState';


// apollo
import { TODOS } from '../client_modules/apollo_client/querys/todos';
import { FetchMoreOptions, FetchMoreQueryOptions, useQuery } from '@apollo/client';
import { ME } from '../client_modules/apollo_client/querys/user';
import useTodos from '../client_modules/hooks/useTodos';







export default function Home() {

  const { state, dispatch } = useGlobalState();
  const { menu, user } = state;

  const { todos } = useTodos();

  const [spinner, setSpinner] = useState(false);


  return (
    <>
      <Head>
        <title>To Do App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavDropDown />
      <TodoDropDown />
      <Navbar />


      <AppLayout>
        <AppLayOutItems>
          <Settings/>
        </AppLayOutItems>
        <AppLayOutItems>
        All Todos
          { user?.data && <ActionButton /> }
          { todos && todos.map(( todo: any, index: number ) => (
            <React.Fragment key={index}>
              <Todos todo={todo} userID={user?.data?.id}/>
            </React.Fragment>
          )) }
        </AppLayOutItems>
      </AppLayout>
      
      
    </>
  )
}
