
// next
import Head from 'next/head';
import { Dropdown } from '../client_modules/components/DropDown/DropDown';

// components
import Navbar from '../client_modules/components/Navbar/Navbar';

// react
import { useContext } from 'react';
import Context from '../client_modules/state_mangement/context';
import { ContextInterface } from '../client_modules/actiontypes';


export default function Home() {

  const { state, dispatch } = useContext(Context) as ContextInterface

  // do you use slack? to work with more jobs, okay ?

  return (
    <>
      <Head>
        <title>To Do App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Dropdown />
      <Navbar />

      <div>
        Hello World
      </div>
    </>
  )
}
