
// next
import Head from 'next/head';
import { useRouter } from 'next/router';

// components
import Navbar from '../client_modules/components/Navbar/Navbar';

// react
import { useEffect } from 'react';
import { useQuery } from '@apollo/client';

// apollo
import { TODOS } from '../client_modules/apollo_client/querys/todos';
import { useGlobalState } from '../client_modules/hooks/useGlobalStateHook';
import NavDropDown from '../client_modules/components/DropDowns/NavDropDown/NavDropDown';




export default function Home() {

  const { state, dispatch } = useGlobalState();
  const { menu } = state




  let offset = 0
  let limit = 10

  const { data: todoData, error: todoError, loading: todoLoading, fetchMore: getMoreTodos } = useQuery(TODOS, {
    variables: {  "offset": offset, "limit": limit }
  });

  useEffect(() => {
    console.log(todoLoading)
    if(todoData) {
      console.log(todoData.todos)
    }
  }, [todoData]);

  return (
    <>
      <Head>
        <title>To Do App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavDropDown />
      <Navbar />


      <div>
        Hello World
      </div>
      
      
    </>
  )
}
